// <auto-generated />
namespace EducationalServices.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Added_notes_into_inspection_and_removed_amount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_notes_into_inspection_and_removed_amount));
        
        string IMigrationMetadata.Id
        {
            get { return "202411191628471_Added_notes_into_inspection_and_removed_amount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
